import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import StoreProvider from "@/redux/StoreProvider";
import Header from "@/components/header/Header";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AOSInit } from "@/aos/Aos";
import Footer from "@/components/footer/Footer";
import { NextAuthProvider } from "./next-auth-provider/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AOSInit />
      <body className={`${inter.className} overflow-x-hidden`}>
        <NextAuthProvider>
          <StoreProvider>
            <Header />
            {children}
            <Footer />
            <ToastContainer />
          </StoreProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
