import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import {store} from "../redux/store"
import StoreProvider from "@/StoreProvider";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className={`${inter.className} overflow-x-hidden`}>
          <StoreProvider>
            <Header/>
            {children}
          </StoreProvider>
        </body>
      </html>
  );
}

